package triangulation;

import java.util.ArrayList;
import sun.java2d.loops.DrawRect;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JPanel;
import sun.java2d.loops.DrawLine;
import java.awt.*;
import java.awt.geom.*;
import javax.swing.*;



/**
 *
 * @author Domino
 */
public class Show extends javax.swing.JFrame {
    Point[] point_cloud;
    Edge[] edges;
    int scale = 11;
    int offset = 50;
    ArrayList circlesA;

    public void paint(Graphics g) {
        //super.paint(g);
float x;
float y;
        //set color to RED
        //So after this, if you draw anything, all of it's result will be RED
        g.setColor(Color.RED);
        //fill circle with RED
        //g.fillOval(100, 100, 5, 5);
 
        try {
            for (int i = 0; i < point_cloud.length; i++) {
                g.fillOval((int)point_cloud[i].getX() * scale + offset, (int)point_cloud[i].getY() * scale + offset, 5, 5);
                g.drawString("" + point_cloud[i].getID(), (int)point_cloud[i].getX() * scale + offset, (int)point_cloud[i].getY() * scale + offset);
            }
        } catch (Exception e) {
        }

        g.setColor(Color.blue);
        try {
            for (int i = 0; i < edges.length; i++) {
                g.drawLine((int)edges[i].l.getX() * scale + offset, (int)edges[i].l.getY() * scale + offset, (int)edges[i].r.getX() * scale + offset, (int)edges[i].r.getY() * scale + offset);
                if (i==0||i==1||i==2) {g.setColor(Color.CYAN);
                    g.drawString("" + point_cloud[i].getID(), (int)point_cloud[i].getX() * scale + offset, (int)point_cloud[i].getY() * scale + offset);
                } else {g.setColor(Color.blue);
                g.drawLine((int)edges[i].l.getX() * scale + offset, (int)edges[i].l.getY() * scale + offset, (int)edges[i].r.getX() * scale + offset, (int)edges[i].r.getY() * scale + offset);
                }
                
                if(edges[i].getMidpoint()!=null)g.setColor(Color.GREEN);g.fillOval((int)edges[i].getMidpoint().getX() * scale + offset, (int)edges[i].getMidpoint().getY() * scale + offset, 5, 5);g.setColor(Color.BLACK);g.drawString(""+i,(int)edges[i].getMidpoint().getX() * scale + offset, (int)edges[i].getMidpoint().getY() * scale + offset);
                //g.drawString(""+i, edges[i].l.getX()*scale+offset, edges[i].r.getY()*scale+offset );
            } 
        } catch (Exception e) {
        }

        g.setColor(Color.ORANGE);
        try {
            for (int i = 0; i < circlesA.size(); i++) {
                Circle circle = (Circle) circlesA.get(i);
                g.drawOval(((int)circle.getX()-(int)circle.getR()) * scale + offset,((int)circle.getY()-(int)circle.getR()) * scale + offset,2*(int)circle.getR() * scale,2*(int)circle.getR() * scale);
            }
        } catch (Exception e) {
        }


    }

    /** Creates new form Show */
    public Show() {
        initComponents();
        System.out.print("aaa");
    }
    
    void Kresli(triangulation.Point[] point_cloud, Edge[] edges, ArrayList circlesA) {
//        paint(new Graphics);
        this.point_cloud=point_cloud;
        this.edges=edges;
        this.circlesA=circlesA;

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
